CLASS ycx_table_cell_not_found DEFINITION INHERITING FROM cx_no_check
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS ycx_table_cell_not_found IMPLEMENTATION.
ENDCLASS.
